### ISSUE TITLE
Unable to use 'mv' plan with a delay motor

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/bluesky-cmds#51]
Bluesky-CMDS gets stuck on some unit conversion error everytime you select a delay for the 'Hardware' of a 'Plan' - 'mv'. Have to close out and restart.

Bluesky-cmds says:

```python
Traceback (most recent call last):
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 407, in <lambda>
    lambda: self.convert(self.units_widget.currentText())
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 326, in convert
    new_val = wt_units.converter(old_val, self.units, str(destination_units))
  File "C:\Users\john\Miniconda3\lib\site-packages\WrightTools\units.py", line 126, in converter
    val = ureg.Quantity(val, current_unit).to(destination_unit).magnitude
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 517, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 462, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 961, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\context\registry.py", line 403, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 254, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 1000, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'picosecond' ([time]) to 'dimensionless' (dimensionless)

```

**Comment by DLafayetteII** [comment]
(Can workaround by running a short gridscan that ends with delay at desired position)

**Comment by ksunden** [comment]
are you selecting e.g. `d1` or `d1_motor`?

The latter is in motor native units (e.g. mm, though somehow this one appears to be dimensionless...)

Is this an internal OPA motor? (I think those ones are actually reported as dimensionless)

Can you select the units as "None"?

**Comment by jscheeler1** [comment]
The same thing is occurring when trying to use the mv plan with an OPA (not an internal OPA motor but the attune version of an OPA with names w1, w2, etc). When changing the hardware to the OPA from d0 (which is the default hardware on the fs table when the mv plan is selected), the error below is returned and bluesky-cmds freezes so the units can't be changed to None.

`Traceback (most recent call last):
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 407, in <lambda>
    lambda: self.convert(self.units_widget.currentText())
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 326, in convert
    new_val = wt_units.converter(old_val, self.units, str(destination_units))
  File "C:\Users\john\Miniconda3\lib\site-packages\WrightTools\units.py", line 126, in converter
    val = ureg.Quantity(val, current_unit).to(destination_unit).magnitude
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 517, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 462, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 961, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\context\registry.py", line 403, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 254, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 1000, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'nanometer' ([length]) to 'dimensionless' (dimensionless)`

The same thing occurs for the monochromator since it has the same units. When trying to mv the nd wheel, the below error is returned but bluesky still works and the mv plan is successfully completed.

`Traceback (most recent call last):
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 407, in <lambda>
    lambda: self.convert(self.units_widget.currentText())
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 331, in convert
    self._set_limits()
  File "C:\Users\john\source\bluesky-cmds\bluesky_cmds\project\classes.py", line 286, in _set_limits
    min_value = wt_units.converter(min_value, limits_units, self.units)
  File "C:\Users\john\Miniconda3\lib\site-packages\WrightTools\units.py", line 126, in converter
    val = ureg.Quantity(val, current_unit).to(destination_unit).magnitude
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 517, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\quantity.py", line 462, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 961, in convert
    return self._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\context\registry.py", line 403, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\nonmultiplicative\registry.py", line 254, in _convert
    return super()._convert(value, src, dst, inplace)
  File "C:\Users\john\Miniconda3\lib\site-packages\pint\facets\plain\registry.py", line 1000, in _convert
    raise DimensionalityError(src, dst, src_dim, dst_dim)
pint.errors.DimensionalityError: Cannot convert from 'picosecond' ([time]) to 'degree' (dimensionless)`

**Comment by ddkohler** [comment]
Sorry have not yet had a chance to play with this on a test system but this looks like the potential culprit:
https://github.com/wright-group/bluesky-cmds/blob/464cc55109adc2fcfd183672f6bcdb4d1f67f122/bluesky_cmds/somatic/plan_ui.py#L518

(i.e. we should use `get_unit(hardware.read())`?"
